# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  ING-zadanie-backend:
    build:
      context: "C:\\Users\\kris102\\Desktop\\moje_projekty\\ING-zadanie"
      dockerfile: "Backend/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Backend.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "backend:dev"
    ports: []
    volumes:
    - "C:\\Users\\kris102\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\kris102\\Desktop\\moje_projekty\\ING-zadanie\\Backend:/app:rw"
    - "C:\\Users\\kris102\\Desktop\\moje_projekty\\ING-zadanie:/src:rw"
    working_dir: "/app"
  ING-zadanie-frontend:
    build:
      context: "C:\\Users\\kris102\\Desktop\\moje_projekty\\ING-zadanie"
      dockerfile: "Frontend/Dockerfile"
      target: "build"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/../../../../.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/8.0.0-rc.2.23480.2/tools/blazor-devserver.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "frontend:dev"
    ports: []
    volumes:
    - "C:\\Users\\kris102\\.nuget\\packages:/root/.nuget/packages"
    - "C:\\Users\\kris102\\Desktop\\moje_projekty\\ING-zadanie\\Frontend:/app:rw"
    - "C:\\Users\\kris102\\Desktop\\moje_projekty\\ING-zadanie:/src:rw"
    working_dir: "/app"
